import type {
  MyShoppingHomeData,
  MyShoppingMenuSection,
  MyShoppingOrder,
} from "./types";
import { createMockImageDataUrl } from "@/lib/utils/mockImage";

export const myShoppingMenuSections: MyShoppingMenuSection[] = [
  { title: "마이쇼핑 홈", path: "/myshop", items: [] },
  { title: "주문/배송내역", path: "/myshop/orders", items: [] },
  { title: "찜한 상품", items: [] },
  { title: "최근 본 상품", items: [] },
  { title: "리뷰 작성", items: ["작성 가능한 리뷰", "내가 작성한 리뷰"] },
  { title: "관심 스토어", items: ["알림 스토어", "가입 라운지"] },
  { title: "정기구독", items: [] },
  { title: "무료체험", items: [] },
  { title: "상품 Q&A", items: [] },
];

export const myShoppingHomeData: MyShoppingHomeData = {
  profile: {
    userName: "조준희님",
    profileLabel: "쇼핑 프로필",
    rewardLabel: "N pay",
    rewardValue: "5,051P",
    benefitLabel: "최대 5% 적립",
  },
  quickLinks: [
    { title: "주문/배송내역", icon: "OD", path: "/myshop/orders" },
    { title: "찜한상품", icon: "LK", path: "/myshop" },
    { title: "리뷰작성", icon: "RV", path: "/myshop" },
    { title: "관심스토어", icon: "ST", path: "/myshop" },
    { title: "보유쿠폰", icon: "CP" },
    { title: "최근본상품", icon: "RC" },
    { title: "상품Q&A", icon: "QA" },
    { title: "자주구매", icon: "RB" },
    { title: "정기구독", icon: "SB" },
    { title: "선물함", icon: "GF" },
    { title: "렌탈", icon: "RT" },
    { title: "무료체험", icon: "FR" },
  ],
  likedProducts: [
    {
      id: "liked-1",
      brand: "atelier morn",
      title: "포근한 호텔식 침구 세트",
      priceLabel: "89,000원",
      accent: "from-[#f7e7d5] to-[#f0c59f]",
      badge: "무료배송",
      imageUrl: createMockImageDataUrl({
        label: "ATELIER",
        startColor: "#f7e7d5",
        endColor: "#f0c59f",
        textColor: "#5a3925",
      }),
    },
    {
      id: "liked-2",
      brand: "wood frame",
      title: "원목 수납형 LED 침대 프레임",
      priceLabel: "243,500원",
      accent: "from-[#eadfce] to-[#c6a78a]",
      badge: "베스트",
      imageUrl: createMockImageDataUrl({
        label: "WOOD",
        startColor: "#eadfce",
        endColor: "#c6a78a",
        textColor: "#4f3826",
      }),
    },
    {
      id: "liked-3",
      brand: "wedding note",
      title: "웨딩 전문 사회자 섭외 패키지",
      priceLabel: "140,300원",
      accent: "from-[#f6edd8] to-[#d8b36c]",
      badge: "추천",
      imageUrl: createMockImageDataUrl({
        label: "WEDDING",
        startColor: "#f6edd8",
        endColor: "#d8b36c",
        textColor: "#5f4614",
      }),
    },
    {
      id: "liked-4",
      brand: "studio live",
      title: "프리미엄 축가 라이브 예약",
      priceLabel: "240,500원",
      accent: "from-[#d8d2ca] to-[#82756d]",
      badge: "인기",
      imageUrl: createMockImageDataUrl({
        label: "LIVE",
        startColor: "#d8d2ca",
        endColor: "#82756d",
        textColor: "#ffffff",
      }),
    },
  ],
};

export const myShoppingOrders: MyShoppingOrder[] = [
  {
    id: "order-1",
    orderNumber: "20251210-0001",
    customerName: "조준희",
    status: "구매확정완료",
    orderedAt: "2025.12.10. 11:28 주문",
    title: "[장사의신 양념] 한우 갈비탕 밀키트 맑은 국밥 600g",
    priceLabel: "10,000원",
    sellerActionLabel: "판매자정보/문의 >",
    imageClass: "from-[#7c5236] via-[#a86a44] to-[#e6d4b9]",
    paymentMethod: "Npay 간편결제",
    shippingAddress: "경기도 성남시 분당구 판교역로 235",
    managementMemo: "재구매율이 높은 상품. 리뷰 유도 쿠폰 발송 완료.",
    channel: "web",
  },
  {
    id: "order-2",
    orderNumber: "20250512-0088",
    customerName: "조준희",
    status: "배송중",
    orderedAt: "2025.05.12. 13:37 주문",
    title: "부산 랜드마크 패키지 해변열차 투어패스 테마파크 이용권",
    priceLabel: "38,900원",
    sellerActionLabel: "판매자정보/문의 >",
    imageClass: "from-[#6c78cc] via-[#8b8fe3] to-[#d9defd]",
    paymentMethod: "신용카드",
    shippingAddress: "서울시 강남구 테헤란로 152",
    managementMemo: "앱 웹뷰 유입 주문. 고객 문의 1건 처리 완료.",
    channel: "app",
  },
  {
    id: "order-3",
    orderNumber: "20260202-1455",
    customerName: "조준희",
    status: "배송준비중",
    orderedAt: "2026.02.02. 09:12 주문",
    title: "프리미엄 소고기 구이용 500g 선물세트",
    priceLabel: "49,800원",
    sellerActionLabel: "판매자정보/문의 >",
    imageClass: "from-[#dcbca2] via-[#c07b57] to-[#8d4f3b]",
    paymentMethod: "Npay 포인트",
    shippingAddress: "서울시 서초구 서초대로 74",
    managementMemo: "출고 대기. 냉장 포장 체크 필요.",
    channel: "web",
  },
  {
    id: "order-4",
    orderNumber: "20260214-2004",
    customerName: "김하늘",
    status: "교환접수",
    orderedAt: "2026.02.14. 17:42 주문",
    title: "케이스티파이 아이폰17 투명 케이스",
    priceLabel: "72,000원",
    sellerActionLabel: "판매자정보/문의 >",
    imageClass: "from-[#dfe5ef] via-[#b0c5e7] to-[#7ea0d7]",
    paymentMethod: "신용카드",
    shippingAddress: "서울시 송파구 올림픽로 300",
    managementMemo: "사이즈 오주문으로 교환 요청. 회수 접수 완료.",
    channel: "app",
  },
];
